### ISSUE TITLE
油管无法判断开台

### ISSUE THREAD

**Issue by 26726673** [magicalz/StreamRecorder#2]
大佬制作项目辛苦了
我在11月时使用都正常但12月开始出现无法正常录制
从档案夹里面发现只有影片叙述和缩图，影片并没有正常录制
拿了正在开台频道做测试发现一直出现
===youtube=== The stream is not available now
===youtube=== Retry after 30 seconds...
看到上一个issue发现可能是油管更改了某些地方
原本想自己试试看有没有办法修复
无奈实在不懂这方面的东西
输入wget -q -O- $LIVE_URL|grep -q '\\"isLive\\":true’(有输入直播网址)
也什么都没出现
再麻烦大佬指点一下问题出在哪里

**Comment by magicalz** [comment]
大概看了下，youtube又有改动了，导致判断开台失效，同时也会导致streamlink无法正常工作
即使我这边改了，streamlink也要等到下一个release才能使用，所以我这边打算暂时先放置，等streamlink新版本出来再做对应改动
streamlink那边的issue link：
https://github.com/streamlink/streamlink/issues/3320

**Comment by agustyuzu** [comment]
插一下，streamlink好像在搞2.0，下一个正式release可能很难等。

请问AWS的lightsail可以搞这个吗？ （AWS配合优惠码好像会特别便宜）一般1G RAM的配的都是20G/25G的存储....

**Comment by magicalz** [comment]
steamlink 2.0版本已经发布，我修改了判断开台的代码以应对youtube的改动，在streamlink 2.0和youtube-dl 2020.12.22下测试通过

**Comment by magicalz** [comment]
录播脚本本身不占用多少系统资源，不过备份上用到了rclone，这是个吃内存大户，512M RAM以上的VPS一般都能满足需求，硬盘肯定是越大越好，另外建议手动添加swap分区，内存的1-2倍大小即可

**Comment by ghost** [comment]
非常感谢大佬的无私帮助！

**Comment by magicalz** [comment]
> 非常感谢大佬的无私帮助！

太客气了，我原来也是一个转播man+烤肉man，不过现在很少烤肉和转播了
看到以前写的小工具还能帮到别人我也很欣慰
有空的话打算用python重写一下，用youtube api来判断是否直播

祝大家圣诞快乐！

**Comment by 26726673** [comment]
感谢大佬的帮助
