### ISSUE TITLE
backup 时文件名的疑问

### ISSUE THREAD

**Issue by zhangaoyun** [magicalz/StreamRecorder#4]
https://github.com/magicalz/StreamRecorder/blob/e881414f37ed913a4f2b69d9e110fdf57ab5fb1e/backuper.sh#L20
这一行最后那里是想用正则表达式吗？不过好像会直接当成文件名，从而上传到网盘时找不到文件。

**Comment by magicalz** [comment]
这是用于BaiduPCS-Go的上传命令的代码，在BaiduPCS-Go项目已经消失的现在，相关代码已经没有用处了，请用rclone上传

**Comment by zhangaoyun** [comment]
我用的是这个 [BaiduPCS-Go](https://github.com/felixonmars/BaiduPCS-Go)，是可以登录和上传文件的。
但如果设置自动备份为 on，`./autorun.sh` 后，在备份上传到百度网盘时 BaiduPCS 的 log 里就会报 `警告: 遍历错误: lstat recorded/yukari/bilibili/20210204/bil_9162799_【雑談】去了一趟医院_20210204_203758.*: no such file or directory
未检测到上传的文件.` 这样的错误。

**Comment by magicalz** [comment]
原版的BaiduPCS-Go是支持以*作为占位符的，你使用的版本我不大清楚
可以手动输入上传命令测试下*占位符是否可以正常使用：BaiduPCS-Go upload "$SAVEFOLDER" "$TARGETPATH"
由于BaiduPCS-Go官方项目已经不存在了，还是建议使用rclone来备份，我可能会在后续更新中移除BaiduPCS-Go的所有相关代码

**Comment by magicalz** [comment]
原版的BaiduPCS-Go是支持以*作为占位符的，你使用的版本我不大清楚
可以手动输入上传命令测试下*占位符是否可以正常使用：BaiduPCS-Go upload "$SAVEFOLDER" "$TARGETPATH"
由于BaiduPCS-Go官方项目已经不存在了，还是建议使用rclone来备份，我可能会在后续更新中移除BaiduPCS-Go的所有相关代码

**Comment by magicalz** [comment]
原版的BaiduPCS-Go是支持以星号作为占位符的，你使用的版本我不大清楚
可以手动输入上传命令测试下星号占位符是否可以正常使用：BaiduPCS-Go upload "$SAVEFOLDER" "$TARGETPATH"
由于BaiduPCS-Go官方项目已经不存在了，还是建议使用rclone来备份，我可能会在后续更新中移除BaiduPCS-Go的所有相关代码

**Comment by magicalz** [comment]
原版的BaiduPCS-Go是支持以星号作为占位符的，你使用的版本我不大清楚
可以手动输入上传命令测试下星号占位符是否可以正常使用：BaiduPCS-Go upload "aaabbb.*" "$TARGETPATH"
由于BaiduPCS-Go官方项目已经不存在了，还是建议使用rclone来备份，我可能会在后续更新中移除BaiduPCS-Go的所有相关代码

**Comment by zhangaoyun** [comment]
我试了下，手动星号占位符也是不可以的，会报同样的错误。
找到了 commit 记录 [#776, 取消上传路径通配符匹配 ](https://github.com/felixonmars/BaiduPCS-Go/commit/dd04fc374b82ded7ab8bdba99309afb6c771a76e)，所以在此之前的版本应该是可用的。

**Comment by magicalz** [comment]
要不你手动改成自己需要上传文件的扩展名吧，.ts或者.mp4，或者使用旧一点的BaiduPCS-Go版本

**Comment by zhangaoyun** [comment]
好的。
此外还有一个 bug，如果生成的视频文件含有空格，会在脚本之间参数传递的过程中丢失空格后的部分：
https://github.com/magicalz/StreamRecorder/blob/e881414f37ed913a4f2b69d9e110fdf57ab5fb1e/recorder.sh#L156
https://github.com/magicalz/StreamRecorder/blob/e881414f37ed913a4f2b69d9e110fdf57ab5fb1e/autobackup.sh#L33
https://github.com/magicalz/StreamRecorder/blob/e881414f37ed913a4f2b69d9e110fdf57ab5fb1e/backuper.sh#L8

**Comment by magicalz** [comment]
其实只有B站是以直播标题为文件名来保存的，直播标题含有空格的情况也不多见，下次更新统一改成不使用直播标题好了

**Comment by zhangaoyun** [comment]
嗯嗯。非常感谢回复，提前祝您新年快乐！

**Comment by zhangaoyun** [comment]
如果想要解决空格的 bug，传递参数时加上双引号就行了。

**Comment by magicalz** [comment]
空格只是小问题，不使用标题作为文件名是为了避免各种不合规范的标题名导致文件上传失败，需要标题可以到备份目录的.info.txt中查看，下次更新会把B站和其他视频网站统一处理
预祝新年快乐！

**Comment by zhangaoyun** [comment]
好的，学到了。
