### ISSUE TITLE
录制上传问题求教

### ISSUE THREAD

**Issue by smoothan** [magicalz/StreamRecorder#7]
请问录制保存的视频如何上传到onedrive上，已经按照您教程的步骤用rclone挂载了onedrive，看screen进程有录制，但是onedrive云盘上里没有上传文件

**Comment by smoothan** [comment]
顺便再问一下Twitch录制失败应该怎么办，API已经填写完整，screen显示
stream record fail, check log/chr/twitch/twitch_20210603_131037_39453252475.mp4.log and log/chr/twitch/twitch_20210603_131037_39453252475.mp4.streaming.log for detail
查看log文件没提示

**Comment by magicalz** [comment]
没有log没法帮你具体分析，你的问题多半都是权限问题或者是环境变量问题，先手动试试rclone能否在你的当前用户下正常工作，log文件夹有没有设置成777权限等等

**Comment by smoothan** [comment]
重新安装后问题已经解决了，谢谢！
另外还有一个问题求教，onedrive支持MP4格式的视频播放，我将config里面的格式改为MP4，但是上传的录播在onedrive中在线播放时报错显示该浏览器下视频无法播放。我试着将从网上下载的MP4格式电影传入onedrive则可以直接在线播放。好像录制的视频格式仍为flv
![image](https://user-images.githubusercontent.com/85295619/120893064-c2e79f00-c643-11eb-8918-4d640e42d223.png)

**Comment by magicalz** [comment]
mp4只是个封装格式，里面封装的视频轨具体是什么样的，跟直播网站有关，streamlink其实是调用了ffmpeg来下载直播网站的视频和音频，然后再封装成mp4，并没有改变源视频的格式。而有些直播网站的视频onedrive可以播放，有些不能播放很正常

**Comment by smoothan** [comment]
哦哦明白了，谢谢大佬帮助
